gameWindow = document.querySelector("#gameDiv");

let playerX = 0;
let playerY = 0;

// 0 = trees
// 1 = grass
// 2 = beach
// 3 = coast
// 4 = ocean
let gameMap = [
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]]
]

function renderMap() {
    for (let x = 0; x < 40; x++) {
        for (let y = 0; y < 40; y++) {
            let storage = document.createElement("div");
            let base = document.createElement("img");
            let more = document.createElement("img");

            base.className = "gameImg";
            base.className = "gameImg";

            storage.style.position = "relative";

            base.src = "sprites/" + gameMap[x][y][0] + ".gif";
            more.src = "sprites/" + gameMap[x][y][1] + ".png";

            base.left = x * 8;
            base.top = y * 8;
            more.left = x * 8;
            more.top = y * 8;

            storage.appendChild(base);
            storage.appendChild(more);

            document.getElementById("gameDiv").appendChild(storage);
        }
    }

    let player = document.createElement("img");
    player.className = "gameImg";
    player.src = "sprites/player.png";
    player.left = playerX * 8;
    player.top = playerY * 8;

    document.getElementById("gameDiv").appendChild(player);
}

window.addEventListener("keypress", function (e) {
    renderMap();
})