gameWindow = document.querySelector("#gameDiv");

let playerX = 0;
let playerY = 0;

// 0 = trees
// 1 = grass
// 2 = beach
// 3 = coast
// 4 = ocean
let gameMap = [
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["trees", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["trees", 0], ["trees", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0]],
    [["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["grass", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]],
    [["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["beach", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["coast", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0], ["ocean", 0]]
]

function renderMap() {
    for (let x = 0; x < 40; x++) {
        for (let y = 0; y < 40; y++) {
            let base = document.createElement("img");
            let more = document.createElement("img");

            base.className = "gameImg";
            base.className = "gameImg";

            base.src = "sprites/" + gameMap[x][y][0] + ".gif";
            more.src = "sprites/" + gameMap[x][y][1] + ".png";

            base.left = x * 4;
            base.top = y * 4;
            more.left = x * 4;
            more.top = y * 4;

            document.getElementById("gameDiv").appendChild(base);
            document.getElementById("gameDiv").appendChild(more);
        }
    }

    let player = document.createElement("img");
    player.className = "gameImg";
    player.src = "sprites/player.png";
    player.left = playerX * 4;
    player.top = playerY * 4;

    document.getElementById("gameDiv").appendChild(player);
}

window.addEventListener("keypress", function (e) {
    renderMap();
})